### ISSUE TITLE
3 TB SYMW

### ISSUE THREAD

**Issue by loppefaaret** [themaddoctor/linux-mybook-tools#1]
just successfully accessed a 3 TB my book, originating from a Symware chip - recomend adding 3 TB disk sector location for the tutorial (skip=5860529539)
when you direct people to ./unwrap.py script, perhaps you want to expect that people are in ./wd/ directory, and therefor start it with ../unwrap.py instead, along with chmod +x ../unwrap.py
and before i could get pycrypto to install, i had to do some minor dependencies

and perhaps a section for people that have had the disk connected to windows, and thereby corrupted the MBR / GPT - or a link to a recommended guide

oh, and a big thank you!!

**Comment by themaddoctor** [comment]
Thank you for the keyblock location.

Most people use a package manager to install software, so dependencies come automatically. I think that the only one is SSL, and if OpenSSL is installed when you compiled Python, then pyopenssl is built automatically. Or did you find that you needed something else?

There is a section at the end for bypassing a corrupt MBR.

**Comment by loppefaaret** [comment]
i missed that last section about the corrupt mbr, my apoligies!
i was on ubuntu 17.04, and never used python scripts before, or python really for that matter... 
i just needed to make sure that everything was installed and working before i tried to access the drive for data... i just google ubuntu pycrypto - and followed this:
https://stackoverflow.com/questions/11596839/installing-pycrypto-on-ubuntu-fatal-error-on-build
after doing the toturial, i had access to /dev/mapper/wd - i installed testdisk - and are currently accessing data through testdisk(list files), recovering to another disk - i tried rebuilding the MBR with testdisk, but i think a misconfiguration inside testdisk has made something not work correctly (heads,cylinder,sectors) cause mount said something about the NTFS was missing some info...
the terminal window is currently running testdisk, but i will return with more data once im done doing the backup - 
would you have any use of the first 2MB of the disk ? want me to hexdump it in a comment ?

**Comment by themaddoctor** [comment]
If you try the loop-device method, you might not need testdisk. Try that before dumping.

Regarding python, you had trouble because you were building the pycrypto module yourself, rather than installing it through your package manager. Ubuntu has a prebuilt package for it.

**Comment by loppefaaret** [comment]
the loop-device method worked perfectly for mounting it...
although there was a referal to /dev/sd**a** which i believe should had been /dev/sd**c**
