### ISSUE TITLE
My Passport Studio

### ISSUE THREAD

**Issue by suddenlykevin** [themaddoctor/linux-mybook-tools#103]
Hi there! First of all, thanks so much for this invaluable resource on retrieving lost data on encrypted WD drives.

I have a 1TB WD My Passport Studio which I used with my Mac whose board burnt out a while back, so I shucked the drive thinking I could plug it in using a SATA-USB adapter later on. It was not password protected, but it seems like the data is inaccessible when using an adapter (I connected the drive to a Windows computer, which may have been a mistake, but made sure to reject any options to reconfigure etc.).

I have a Linux machine (Mac Mini flashed with ubuntu) and was looking into the steps you had in your PDF but immediately ran into a problem in step 1, which is that `sudo file -s /dev/sda` returns `/dev/sda: DOS/MBR boot sector; partition 1 : ID=0xee start-CHS (0x0,0,2), end-CHS (0x30,254,63), startsector 1, 424967295 sectors, extended partition table (last)`. So I assume that means Windows might've done something to my drive nonetheless?

I tried following the steps anyways, but the result of `sudo file -sL /dev/mapper/wd` is `/dev/mapper/wd: data` and `sudo file -s /dev/mapper/wd` is `/dev/mapper/wd: symbolic link to ../dm-0`.

Following the instructions for mounting a loop device ends with the result `mount: /mnt/wd: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error`

Any assistance you can offer would be much appreciated. Thanks!

**Comment by themaddoctor** [comment]
Which chip does it have?
What is your DEK?
Do a hexdump of sectors 2048 and 2049:
sudo dd if=/dev/sda skip=2048 count=2 status=none | hexdump -C

**Comment by suddenlykevin** [comment]
Thanks for the response. Looks like the original enclosure had a PLX OXUF943SE chip. The DEK I got was `c3c1288ee6616338f8867a2c6e72a11a087ae0c5fa440585e0bf8aaa1b2847e8` but the hexdump doesn't seem to show anything:
`00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400
`

Also wanted to note Disks seems to show that there is a 17MB "Microsoft Reserved" partition that is mounted to /dev/sda1

**Comment by suddenlykevin** [comment]
dumping from sector 0:
sudo dd if=/dev/sdb count=10 status=none | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001b0  00 00 00 00 00 00 00 00  60 e1 1e 64 00 00 00 00  |........`..d....|
000001c0  02 00 ee fe ff 00 01 00  00 00 ff ff ff ff 00 00  |................|
000001d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
00000200  45 46 49 20 50 41 52 54  00 00 01 00 5c 00 00 00  |EFI PART....\...|
00000210  12 a4 fb 9d 00 00 00 00  01 00 00 00 00 00 00 00  |................|
00000220  af 6d 70 74 00 00 00 00  22 00 00 00 00 00 00 00  |.mpt....".......|
00000230  8e 6d 70 74 00 00 00 00  23 7d 1d 5a 1a 1e 9a 4a  |.mpt....#}.Z...J|
00000240  a6 35 c6 02 a8 7a 52 14  02 00 00 00 00 00 00 00  |.5...zR.........|
00000250  80 00 00 00 80 00 00 00  4f 23 01 95 00 00 00 00  |........O#......|
00000260  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400  16 e3 c9 e3 5c 0b b8 4d  81 7d f9 2d f0 02 15 ae  |....\..M.}.-....|
00000410  77 16 35 36 19 97 48 4c  ab c5 e1 03 80 35 bf 87  |w.56..HL.....5..|
00000420  22 00 00 00 00 00 00 00  ff 7f 00 00 00 00 00 00  |"...............|
00000430  00 00 00 00 00 00 00 00  4d 00 69 00 63 00 72 00  |........M.i.c.r.|
00000440  6f 00 73 00 6f 00 66 00  74 00 20 00 72 00 65 00  |o.s.o.f.t. .r.e.|
00000450  73 00 65 00 72 00 76 00  65 00 64 00 20 00 70 00  |s.e.r.v.e.d. .p.|
00000460  61 00 72 00 74 00 69 00  74 00 69 00 6f 00 6e 00  |a.r.t.i.t.i.o.n.|
00000470  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

**Comment by themaddoctor** [comment]
You probably had an HFS+ partition. Maybe the GPT partition table knows where it is. Try things like
gdisk -l /dev/sda
gdisk -l /dev/mapper/wd

The instruction in the PDF assume an NTFS Windows filesystem.

**Comment by suddenlykevin** [comment]
```
GPT fdisk (gdisk) version 1.0.5

The protective MBR's 0xEE partition is oversized! Auto-repairing.

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/sdb: 1953525168 sectors, 931.5 GiB
Model: TPVT-00U4RT1    
Sector size (logical/physical): 512/4096 bytes
Disk identifier (GUID): 5A1D7D23-1E1A-4A9A-A635-C602A87A5214
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 1953525134
Partitions will be aligned on 8-sector boundaries
Total free space is 1953492367 sectors (931.5 GiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              34           32767   16.0 MiB    0C01  Microsoft reserved ...
```
Does this mean the partition starts at 32767?
```
GPT fdisk (gdisk) version 1.0.5

Partition table scan:
  MBR: not present
  BSD: not present
  APM: not present
  GPT: not present

Creating new GPT entries in memory.
Disk /dev/mapper/wd: 1953525168 sectors, 931.5 GiB
Sector size (logical/physical): 512/4096 bytes
Disk identifier (GUID): 6D08D07D-32BA-49B6-B6DE-BC956B15B978
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 1953525134
Partitions will be aligned on 2048-sector boundaries
Total free space is 1953525101 sectors (931.5 GiB)

Number  Start (sector)    End (sector)  Size       Code  Name

```

**Comment by themaddoctor** [comment]
That's where you could start. To remove a loop device, use "loop -d /dev/loopX"
where X is whatever.

The offset (-o) in the command that sets up a loop device is in bytes. Each sector is 512 bytes.

To mount HFS+, I think you need to add "-t hfsplus" to the mount command.

**Comment by suddenlykevin** [comment]
Based on https://askubuntu.com/questions/332315/how-to-read-and-write-hfs-journaled-external-hdd-in-ubuntu-without-access-to-os, installed hfsprogs before running mount with the -t option. In theory, I should run the "Mounting with a loop device" steps in increments up from `32767*512` in blocks of `512` until no error is returned?

**Comment by themaddoctor** [comment]
Yes, but for mounting, don't forget "-t hfsplus" (or whatever the internet says to use).

I don't have any Mac disks to experiment with, unfortunately.

**Comment by suddenlykevin** [comment]
No luck yet, but I was actually able to recover a few files just using the dek I extracted following your instructions, which is a good sign. Presumably, if I'm hitting JPEG files, though, I'm ahead of the HFS+ partition header so I'm searching in the wrong direction...

**Comment by suddenlykevin** [comment]
I think I just stumbled on the location of the HFS+ volume header based on the specification detailed here: http://dubeyko.com/development/FileSystems/HFSPLUS/hexdumps/hfsplus_volume_header.html, at offset 263970:
```
00000000  48 2b 00 04 80 00 21 00  48 46 53 4a 00 00 1d 1c  |H+....!.HFSJ....|
00000010  ca 42 55 d4 df 31 9b 5e  00 00 00 00 ca 42 b8 44  |.BU..1.^.....B.D|
00000020  00 04 05 59 00 00 49 34  00 00 10 00 0e 8d 6c 1a  |...Y..I4......l.|
00000030  03 bd 3f 0a 0c 36 ea 35  00 01 00 00 00 01 00 00  |..?..6.5........|
00000040  00 0b e0 72 02 67 8c 25  00 00 00 00 02 00 00 8b  |...r.g.%........|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  73 bc 8a ba 29 ad 57 ca  |........s...).W.|
00000070  00 00 00 00 01 d1 b0 00  01 d1 b0 00 00 00 1d 1b  |................|
00000080  00 00 00 01 00 00 1d 1b  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000000c0  00 00 00 00 00 b0 00 00  00 b0 00 00 00 00 0b 00  |................|
000000d0  00 00 6d 1d 00 00 0b 00  00 00 00 00 00 00 00 00  |..m.............|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000110  00 00 00 00 0b 40 00 00  03 c0 00 00 00 00 b4 00  |.....@..........|
00000120  00 00 78 1d 00 00 78 00  00 00 f8 5b 00 00 3c 00  |..x...x....[..<.|
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000160  00 00 00 00 03 c0 00 00  03 c0 00 00 00 00 3c 00  |..............<.|
00000170  00 07 2f e4 00 00 3c 00  00 00 00 00 00 00 00 00  |../...<.........|
00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

**Comment by themaddoctor** [comment]
Very good. Are you able to mount it?

**Comment by suddenlykevin** [comment]
Not yet, tried setting losetup -o to 263970 and mounting with -t hfsplus but no dice. Heading offline for a while, but seems promising!

**Comment by suddenlykevin** [comment]
Was able to completely restore the contents of the disk by using dd_rescue to clone /dev/mapper/wd to a new disk and having testdisk repair and write a new partition table. For future reference to anyone in the same situation, there's no need to dig around for the HFS+ header since testdisk will do this for you. Much time wasted but glad I was able to find a resolution. Thanks again for this resource!

**Comment by themaddoctor** [comment]
That's good news. Glad it worked.

I won't stop you if you would like to send me a book. (you are not obligated at all)
https://www.amazon.com/hz/wishlist/ls/1M9FEQ1ZPGMIE
