### ISSUE TITLE
the readme mentions a tutorial, but I can't find it

### ISSUE THREAD

**Issue by sypernova6969** [themaddoctor/linux-mybook-tools#14]
hi!
got an issue with my WD essential, like everyone the world with one. 
I found how you can read the data in linux with the programs you've made (or a least organised)
I'm 100% new to linux i'm only doing this to be able to do this (I've done tons of windows stuff and a lot of android, so i'm ok with following instructions). 
the only problem is, I see a lot of files in your github, and you mention a tutorial, but I can't find the tutorial, and I don't know how to use all your files, or programs, or whatever they are (lines of code for the prompt command in linux?).
I'd appreciate if you could just explain to me how to get to the tutorial, and I (hopefully Iwill be able to learn as I go.
thanks a lot!
sebastien.
PS: i'm also new to github, which might explain why I can't find the tutorial.  I'm only here for this, I'm not a programmer

**Comment by themaddoctor** [comment]
It's the single PDF file.

**Comment by sypernova6969** [comment]
sh.t  how could I miss that.
I feel like a moron...
thanks. and by the way,, having done this and helping others is super cool.  i'm guessing you've save tons of people's lives (metaphorically;  their photos, work files and projects and everything).  really nice of you.
s.
