### ISSUE TITLE
Data Recovered!!! minor issue on appendix D

### ISSUE THREAD

**Issue by BoBMrTD** [themaddoctor/linux-mybook-tools#19]
Hi,
I've rescued all the data from my WD 2TB enclosure using linux-mybook-tools
My set-up
Live edubuntu 14.04
MAC OSX High Sierra
JMicron JMS538S chip
to obtain the dek.hex key I've used the procedure from
https://github.com/andlabs/reallymine
to build the encryption filter and mount as loop device the disk the procedure from linux-mybook-tools

Only a minor issue:
to be able to compile the script from appendix D I've removed the ending #end preprocessor directive from the program.
 
Thank's @themaddoctor

**Comment by themaddoctor** [comment]
Thanks. It was a stupid error.
