### ISSUE TITLE
Please help sending 2MB blocks

### ISSUE THREAD

**Issue by jvillarrealn** [themaddoctor/linux-mybook-tools#2]
Hello ThemadDoctor,

I want to submit what you ask on the read me file,  the first 2MB of the drive and the keyblock (i did not set a password).
for the first 2MB of the drive, would it be something like this?:
dd if=/dev/sdc bs=2097152 skip=0 count=1 of=xxx.bin

for the keyblock i can paste it here right?.

I'm new to Linux, thanks for your patience.

**Comment by themaddoctor** [comment]
that's one way to do it

**Comment by jvillarrealn** [comment]
@themaddoctor  i was just reading a very long post on the reallymine forum (#42),  where you are trying to help somebody that might be on my same situation. 
I also have 2 partitions,  i was using my external drive on a popcorn video box which only accepted up to 2TB, so i created a 2TB partition.  I never took the drive out of the enclosure, so the partition was done in  Windows but with the SATA to USB bridge in place and since i took it out of the enclosure, i've never attempted to connected to Windows.   
I saw that you asked many things from him to try to help him,  please let me know if i can provide more information my drive.
I have a problem,  my Raspberry PI is in one side and i can't just dump the info here as a "paste", i have to be sending ZIP files.  
i appretieate you time.
