### ISSUE TITLE
Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y error

### ISSUE THREAD

**Issue by dmpsuen** [themaddoctor/linux-mybook-tools#20]
Hi,

I am following your instruction to decrypt my MyBook 3TB which has problem and it can only read max 700Kb/s. I have 2TB data and getting it out with this speed is unthinkable. I took the hard drive out and plug to a LInux Mint box. Here is what I did and I got error on the make and the outcome has bad partition table error.

Thanks for your help!

---
dmp@dmp-main /media/dmp/MyStorage1S $ sudo file -s /dev/sdb
[sudo] password for dmp:
/dev/sdb: data
dmp@dmp-main /media/dmp/MyStorage1S $ cd
dmp@dmp-main ~ $ mkdir wd
dmp@dmp-main ~ $ cd wd
dmp@dmp-main ~/wd $ echo 03141592653589793238462643383279fcebea6d9aca7686cdc7b9d9bcc7cd86 > kek.hex
dmp@dmp-main ~/wd $ sudo dd if=/dev/sdb  bs=512 skip=5860528160 count=1 of=kb.bin
1+0 records in
1+0 records out
512 bytes copied, 1.73554 s, 0.3 kB/s
dmp@dmp-main ~/wd $ hexdump -C kb.bin
00000000  57 44 76 31 ca 12 00 00  00 a0 4f 5d 01 00 00 00  |WDv1......O]....|
00000010  03 00 00 00 00 00 f0 00  00 00 00 00 00 00 00 00  |................|
00000020  01 00 00 00 00 00 46 50  00 00 00 00 00 00 00 00  |......FP........|
...
00000200
dmp@dmp-main ~/wd $ cat kek.hex | grep -o .. | tac | echo "$(tr -d '\n')" > kek1.hex
dmp@dmp-main ~/wd $ for i in `seq 0 31`; do
>  dd if=kb.bin bs=16 count=1 skip=$i status=none | \
>  xxd -p | grep -o .. | tac | echo "$(tr -d '\n')" | \
>  xxd -p -r >> kb1.bin
>  done
dmp@dmp-main ~/wd $ openssl enc -d -aes-256-ecb -K `cat kek1.hex` \
>  -nopad -in kb1.bin -out kb2.bin
dmp@dmp-main ~/wd $ for i in `seq 0 31`; do
>  dd if=kb2.bin bs=16 count=1 skip=$i status=none | \
>  xxd -p | grep -o .. | tac | echo "$(tr -d '\n')" | \
>  xxd -p -r >> kb3.bin
>  done
dmp@dmp-main ~/wd $ hexdump -C kb3.bin
00000000  8e 09 89 29 21 97 57 95  52 3e b3 4b 63 2f 98 72  |...)!.W.R>.Kc/.r|
...
000000f0  ec 00 00 00 c4 00 00 00  fa 00 00 00 05 00 00 00  |................|
00000100  44 45 4b 31 fd b1 00 00  f0 65 be 69 ac 7b 3d 27  |DEK1.....e.i.{='|
00000110  53 04 ef d7 58 ab e3 59  58 45 ce af a9 85 76 3e  |S...X..YXE....v>|
...
00000200
dmp@dmp-main ~/wd $ dd if=kb3.bin bs=1 skip=268 count=16 of=dek0.bin status=none
dmp@dmp-main ~/wd $ dd if=kb3.bin bs=1 skip=288 count=16 status=none >> dek0.bin
dmp@dmp-main ~/wd $ xxd -p -c 32 dek0.bin | grep -o .. | tac | \
>  echo "$(tr -d '\n')" > dek.hex
dmp@dmp-main ~/wd $
dmp@dmp-main ~/wd $ echo | sudo cryptsetup -d - -c rev16-ecb \
>  create wd-layer1 /dev/sdb
device-mapper: reload ioctl on wd-layer1 failed: No such file or directory
dmp@dmp-main ~/wd $ vi rev16.c
dmp@dmp-main ~/wd $ uname -r
4.15.0-30-generic

dmp@dmp-main /lib/modules/4.15.0-30-generic/kernel/crypto $ cd
dmp@dmp-main ~ $ cd wd

dmp@dmp-main ~/wd $ echo "obj-m := rev16.o" > Makefile
dmp@dmp-main ~/wd $ make -C /lib/modules/`uname -r`/build M=$PWD
make: Entering directory '/usr/src/linux-headers-4.15.0-30-generic'
Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /home/dmp/wd/rev16.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/dmp/wd/rev16.mod.o
  LD [M]  /home/dmp/wd/rev16.ko
make: Leaving directory '/usr/src/linux-headers-4.15.0-30-generic'
dmp@dmp-main ~/wd $ sudo insmod rev16.ko
dmp@dmp-main ~/wd $ echo | sudo cryptsetup -d - -c rev16-ecb \
>  create wd-layer1 /dev/sdb
dmp@dmp-main ~/wd $ cat dek.hex | xxd -p -r | sudo cryptsetup -d - --hash=plain \
>  --key-size=256 -c aes-ecb create wd-layer2 /dev/mapper/wd-layer1
dmp@dmp-main ~/wd $ echo | sudo cryptsetup -d - -c rev16-ecb \
>  create wd /dev/mapper/wd-layer2
dmp@dmp-main ~/wd $ sudo file -sL /dev/mapper/wd
/dev/mapper/wd: DOS/MBR boot sector MS-MBR XP english at offset 0x12c "Invalid partition table" at offset 0x144 "Error loading operating system" at offset 0x163 "Missing operating system", disk signature 0x28375; partition 1 : ID=0x7, start-CHS (0x0,4,5), end-CHS (0x3ff,254,63), startsector 256, 732558080 sectors
dmp@dmp-main ~/wd $

**Comment by dmpsuen** [comment]
I tried but it still not working:

dmp@dmp-main ~/wd $ sudo fdisk -l /dev/mapper/wd
Disk /dev/mapper/wd: 2.7 TiB, 3000592982016 bytes, 5860533168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x00028375

Device               Boot Start       End   Sectors   Size Id Type
/dev/mapper/wd-part1        256 732558335 732558080 349.3G  7 HPFS/NTFS/exFAT
dmp@dmp-main ~/wd $ sudo kpartx -a /dev/mapper/wd
dmp@dmp-main ~/wd $ sudo mkdir -p /mnt/wd
dmp@dmp-main ~/wd $ sudo mount /dev/mapper/wd1 /mnt/wd
mount: wrong fs type, bad option, bad superblock on /dev/mapper/wd1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
dmp@dmp-main ~/wd $

**Comment by dmpsuen** [comment]
Thanks for your help. I can read the disk but it looks like it is the hard drive got problem, not he usb controller. I can copy files but it is like 30Kb/s, which is too too slow. :(

Not sure if there is another way to recover my data...

**Comment by themaddoctor** [comment]
You could connect it to an internal SATA port.

I'm closing this issue now. Good luck.
