### ISSUE TITLE
Appendix D

### ISSUE THREAD

**Issue by kalshebikalim** [themaddoctor/linux-mybook-tools#23]
i cant seem to build the kernel i keep getting errors:
(Fedora 24)
[root@localhost me]# make -C /lib/modules/`uname -r`/build M=$PWD
make: Entering directory '/usr/src/kernels/4.11.12-100.fc24.x86_64'
  CC [M]  /root/me/rev16.o
/root/me/rev16.c:77:3: error: invalid preprocessing directive #end
 # end
   ^~~
scripts/Makefile.build:300: recipe for target '/root/me/rev16.o' failed
make[1]: *** [/root/me/rev16.o] Error 1
Makefile:1496: recipe for target '_module_/root/me' failed
make: *** [_module_/root/me] Error 2
make: Leaving directory '/usr/src/kernels/4.11.12-100.fc24.x86_64'

**Comment by themaddoctor** [comment]
I fixed that in the latest PDF about 2 months ago.

**Comment by kalshebikalim** [comment]
thanks
