### ISSUE TITLE
Mounting the drive

### ISSUE THREAD

**Issue by kalshebikalim** [themaddoctor/linux-mybook-tools#24]
[root@localhost wd]# kpartx -a /dev/mapper/wd
this command isnt doing anything i left it running for a several hours and its not doing anything

using -l does list the partition
[root@localhost wd]# kpartx -l /dev/mapper/wd
wd1 : 0 3906961408 /dev/mapper/wd 2048

**Comment by themaddoctor** [comment]
then try the last section , mounting with loop device

**Comment by kalshebikalim** [comment]
[root@localhost wd]# sudo mount /dev/loop1 /mnt/wd
mount: /mnt/wd: wrong fs type, bad option, bad superblock on /dev/loop1, missing codepage or helper program, or other error.

**Comment by kalshebikalim** [comment]
[root@localhost wd]# sudo mount /dev/loop1 /mnt/wd
mount: /mnt/wd: wrong fs type, bad option, bad superblock on /dev/loop1, missing codepage or helper program, or other error.

**Comment by kalshebikalim** [comment]
i did what i saw u tell someone else to do "dd if=/dev/sdb count=2048 of=start.bin" and i saw it was only 1MB so i changed it to 4096 and sent it also
[start.zip](https://github.com/themaddoctor/linux-mybook-tools/files/2444595/start.zip)
[start1.zip](https://github.com/themaddoctor/linux-mybook-tools/files/2444596/start1.zip)

[dek.zip](https://github.com/themaddoctor/linux-mybook-tools/files/2444598/dek.zip)

**Comment by themaddoctor** [comment]
You have the wrong key. You made a typographical error along the way.

If you sent me your keyblock, I could check it.

**Comment by kalshebikalim** [comment]
[kb.zip](https://github.com/themaddoctor/linux-mybook-tools/files/2444604/kb.zip)

**Comment by kalshebikalim** [comment]
i just tried it again for the 5th time and it mounted with a loop device
thank u so much!!!!!!!!
