### ISSUE TITLE
Replacing the PCB with an Identical PCB

### ISSUE THREAD

**Issue by randomroh** [themaddoctor/linux-mybook-tools#25]
Hi Thomas, I really appreciate all the help & support you are providing to us people who would simply just dump the disk.

Im in a similar situation…
To put it briefly,

I stumbled on these posts, after I bought a new HDD Enclosure.
So i connected the “Bare Disk” to windows 10, where it gave me an option to initialize the disk under Disk Management. I clicked Initialize then it asked me to create Partition, thats when i disconnected the disk, without creating any partitions.

Now, My bridge has the “Inic-1607E” chip.
And ive managed to find another disk, with the same HW & PW number. So chances are the other disk will have this same Bridge, in working condition.

I have no Partitions, and No Passwords, but have Almost 1TB of data on this 1TB Disk… in more than 200 directories. So …

… my Questions are …

> Will my disk work and will I be able to recover my data, upon swapping the Bridge ?
> Or the MBR is corrupted, and i have to follow the tutorial.
OR
> How should I proceed , I just want to recover my data… thats it.
Any inputs will be highly appreciated.

Regards
-R

**Comment by themaddoctor** [comment]
I think when you clicked "initialize" you may have ruined your chances. To know for certain, I need to see your keyblock and the first 2MB of the disk. I suggest you follow the tutorial and use the option to mount with a loopback device. If it doesn't work, send me the keyblock and 2MB dump. You can make the dump with something like "sudo dd if=/dev/sdb count=4096 of=dump.bin"

**Comment by randomroh** [comment]
Hi Thomas,
Thankyou for replying.

I followed the instructions in the PDF, and have successfully retrieved the KB.

I have, with effort, completed the part of inserting the module in Kernel.

Now, browsing back to the Initio chip instructions, this command
`echo | sudo cryptsetup -d - -c rev4-ecb`
 gives
`cryptsetup: Arguement <action> missing`

Im aware you asked me to skip directly to "mount with a loopback device", but i wanted to check.

PLEASE Let me know how to proceed from this point onwards.

**Comment by randomroh** [comment]
Heres the KB
`00000000  57 44 01 14 00 00 00 00  02 02 00 00 00 00 00 00  |WD..............|
00000010  00 00 00 00 74 5b 78 00  00 00 00 00 74 5b 78 00  |....t[x.....t[x.|
00000020  00 00 00 00 00 14 e0 00  20 00 00 00 00 00 00 00  |........ .......|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 57 44 01 14  |............WD..|
00000040  13 3c d5 3c ed 9a 64 4e  c8 e9 b0 3a 5a f4 32 36  |.<.<..dN...:Z.26|
00000050  59 b6 72 61 8b 4e c7 08  a7 3a 43 6c 2c 6b c2 07  |Y.ra.N...:Cl,k..|
00000060  6a cc 96 c3 07 de 3a 75  f3 5e fa bf 6d 6f 05 c8  |j.....:u.^..mo..|
00000070  45 fc 73 82 65 11 cd e0  c2 e0 bb 89 c2 3f 19 dc  |E.s.e........?..|
00000080  4d c9 1e 6f 91 57 a3 3b  56 9f f1 1f 6a 25 a0 7c  |M..o.W.;V...j%.||
00000090  76 04 6f 7f 78 20 53 fc  9e a8 f0 6e 5e 4a 5b 41  |v.o.x S....n^J[A|
000000a0  f6 b2 cd 23 5d ae 0d 32  4c 24 ee 39 84 e9 82 2b  |...#]..2L$.9...+|
000000b0  30 ed bd e9 3a f8 0c d4  2d 97 9a de a9 d3 80 1c  |0...:...-.......|
000000c0  44 8f 2e 0a 1c 3e a2 6a  7b b2 2c ab d1 d2 c7 83  |D....>.j{.,.....|
000000d0  a3 9d 5c 0e 79 78 cb 5f  19 73 b0 06 99 b6 aa 1f  |..\.yx._.s......|
000000e0  81 db 67 77 08 61 b0 03  08 d2 c3 5d 12 2d c3 d9  |..gw.a.....].-..|
000000f0  9c f8 be 0a 55 cf 83 5e  00 b3 95 33 e9 b8 07 6b  |....U..^...3...k|
00000100  d1 17 fc bd 5e 43 18 bb  eb b3 81 a7 9e 6e 47 7e  |....^C.......nG~|
00000110  ea ed 23 60 25 94 dd 8b  de 09 78 8b 07 c9 d7 0e  |..#`%.....x.....|
00000120  88 3a 1c 32 02 e8 e4 b5  f9 ca 79 e4 b9 94 23 f1  |.:.2......y...#.|
00000130  83 19 ba 53 89 05 53 60  ce 9b f8 6d f4 57 f6 e9  |...S..S`...m.W..|
00000140  9e 55 35 1f 8a bd 5a 8f  3c 7e 7d 55 68 68 35 29  |.U5...Z.<~}Uhh5)|
00000150  c0 4f 31 75 62 c4 30 44  ec 6d e8 9b 23 a8 d9 64  |.O1ub.0D.m..#..d|
00000160  c4 23 a5 f1 cc 09 13 79  0c 8b 86 55 47 12 16 e2  |.#.....y...UG...|
00000170  1c 92 c9 da 88 64 d8 9e  70 93 8c 58 1c d6 f6 a9  |.....d..p..X....|
00000180  9f 2b e6 64 47 79 71 0c  68 2c a3 93 e9 1b 11 57  |.+.dGyq.h,.....W|
00000190  90 29 4c 68 cd 92 be 90  99 39 05 ce 9d 22 14 19  |.)Lh.....9..."..|
000001a0  04 b8 b5 4b 46 71 3c 9a  08 19 09 ba 08 fe 17 69  |...KFq<........i|
000001b0  a9 b4 06 5c 2b 23 cf 71  f7 2e b9 dc 84 6e 46 64  |...\+#.q.....nFd|
000001c0  39 3a d0 b0 1f 52 b7 03  7b f5 3b db 97 c1 46 65  |9:...R..{.;...Fe|
000001d0  63 91 a6 49 42 de 4c 39  24 70 39 b6 52 3f 5c 28  |c..IB.L9$p9.R?\(|
000001e0  77 bc 1c ee f5 71 2a 6e  c5 ab 9a 12 5e c8 e8 cd  |w....q*n....^...|
000001f0  c7 d4 58 7a 85 1d ec 41  66 f9 ed 49 df a6 d5 f1  |..Xz...Af..I....|
00000200`

**Comment by themaddoctor** [comment]
"Now, browsing back to the Initio chip instructions, this command
echo | sudo cryptsetup -d - -c rev4-ecb
gives
cryptsetup: Arguement <action> missing"

Sorry, there was a backslash missing. The command is continued on the next line. The full command is

echo | sudo cryptsetup -d - -c rev4-ecb create wd-layer1 /dev/sdc

**Comment by randomroh** [comment]
> echo | sudo cryptsetup -d - -c rev4-ecb create wd-layer1 /dev/sdb
returns
`WARNING: Device /dev/sdb already contains a 'gpt' partition signature`

**Comment by themaddoctor** [comment]
I can't advise you further without the 2MB dump.

**Comment by randomroh** [comment]
Ok,
How do I share the file ?
could you suggest a file host ?

**Comment by randomroh** [comment]
filehosting.org - upload confirmation
Thank you for using our service.
Download link
This is the link to the download page for dump.bin. You can share this link as often as you want:
https://www.filehosting.org/file/details/771780/dump.bin

**Comment by themaddoctor** [comment]
I'm not giving my email address to filehosting.org, nor do I accept their terms of service.

You will just have to find a way to attach it on github.
What does that say below the dashed line?

**Comment by randomroh** [comment]
When I attempt to attach underneath the dashed line, i get file format not supported. Upon renaming to dump.jpg or dump.zip it says file exceeds limit.

Here, TinyHosting doesnt ask for anything..
http://s000.tinyupload.com/index.php?file_id=95830408258544681678

**Comment by randomroh** [comment]
Following the LoopBack Guidance..
`root@linux:~/WD# sudo fdisk -s /dev/mapper/wd fdisk: cannot open /dev/mapper/wd: No such file or directory`

Im not sure **sudo fdisk -s /dev/mapper/wd** will return anything. Where did "wd" in this come from ? Do i have to use something instead of WD ? Applicable in my situation ?

**Comment by themaddoctor** [comment]
Sorry. Start over. Follow the instructions.

**Comment by themaddoctor** [comment]
wd is the device that you created with "echo | sudo cryptsetup -d - -c rev4-ecb create wd-layer1 /dev/sdb"

**Comment by randomroh** [comment]
Ohhhh...

Now started all over again..
upon using
"echo | sudo cryptsetup -d - -c rev4-ecb create wd-layer1 /dev/sdb"

I got and still get 

> Warning : Device /dev/sdb already contains a 'gpt' partition signature.
> Cannot use device /dev/sdb which is in use (already mapped or mounted)

**Comment by randomroh** [comment]
Also, Now..

> root@linux:~# fdisk -l
> Disk /dev/sda: 223.6 GiB, 240057409536 bytes, 468862128 sectors
> Disk model: INTEL SSDSC2BF24
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: dos
> Disk identifier: 0x90a1aeb7
> 
> Device     Boot  Start       End   Sectors   Size Id Type
> /dev/sda1  *      2048    718847    716800   350M  7 HPFS/NTFS/exFAT
> /dev/sda2       718848 468860927 468142080 223.2G 83 Linux
> 
> 
> Disk /dev/sdb: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
> Disk model: EADS-11M2B2     
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: gpt
> Disk identifier: BF32331E-079A-4D16-9885-C4F72CFE703A
> 
> Device     Start   End Sectors Size Type
> /dev/sdb1     34 32767   32734  16M Microsoft reserved

**Comment by randomroh** [comment]
Bump !?

**Comment by themaddoctor** [comment]
When you initialized the disk with Windows, you created a new MBR and empty partition table. Your system is trying now to use that disk. I do not know what system you have. MY system does not automatically try to mount and use disks, so this is not a problem that I encounter.

If sdb appears on the dock in Ubuntu, you can right-click on it and ask it to "eject" the disk. If you use some other system, you will have to figure out what it is doing.

You could try to destroy the MBR that Windows created with this command:
sudo dd if=/dev/zero count=1 of=/dev/sdb
[WARNING: If sdb is not the correct disk or if you mistype "count=1", then you can destroy data.]
Then reboot and try again.

**Comment by randomroh** [comment]
Im using Kali 2.0 with KDE

i was searching the internet for this error..
Strange bit is

umount -f /dev/sdb  gives
not mounted 

umount sdb1 also gives 
not mounted

there are no mount points..
Mount doesnt list this disk/partition

But, 
when browsed to /dev/mapper in file explorer.. there is sdb1 with a butterfly tag/icon on it.
If I simply delete this sdb1 from here, will it unmount ? will it cause any issues ?

Im afraid of deleting / destroying anything from the disk. To be honest, I feel it may ruin my chances to recover anything.. ?

**Comment by randomroh** [comment]
F'MOTHER OF ALL DUCKS !!!!!!!!!!!!!!!!!!!

I LOVE YOU MAN !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I Cant believe my eyes!!!

> After what you mentioned, I plugged the disk usb, typed lsblk to make sure it wasnt there.. then plugged it back again.
> Which now was renamed to SDC instead of SDB..
> then simply completed the rest of instructions!! 

AND I CAN SEEEE MY FILES.. AT LAST!

MY PRECIOUS KEYS.TXT 
HOLY DUCK!!

GOD BLESS YOU THOMAS!

**Comment by themaddoctor** [comment]
YW
