### ISSUE TITLE
2 quick questions

### ISSUE THREAD

**Issue by jvillarrealn** [themaddoctor/linux-mybook-tools#3]
How can i use your program:
sw6316-extract-DEK-from-keyblock.sh?.
how would i run it?  i think it receives 2 parameters right? 

second questions,  the linux on my Raspberry PI, doesn't have the command KPARTX,  what else can i use?
I think my Raspberry Pi has debian.  

thanks

**Comment by themaddoctor** [comment]
You don't need to use the script because I already sent you the DEK.

kpartx is in the multipath-tools package. Google for the correct installation command.

**Comment by jvillarrealn** [comment]
Thanks Doc,  i now know how to install KPARTX.  Will try again with the DEK you sent me and if that doesn't work,  i'll try with the DEK you posted on the Reallymine forum:


"

extracted key:
c3e28b880b87c9c65c62b7250398a1ef926dbf75e6c2779a69d0ac5a9c3c1aeb

corrected for endianness:
888be2c3c6c9870b25b7625cefa1980375bf6d929a77c2e65aacd069eb1a3c9c

"


thanks again.



________________________________

**Comment by themaddoctor** [comment]
You are Javier, correct?

Your DEK is unique to your disk. No other DEK will work.

bash sw6316-extract-DEK-from-keyblock.sh <kek file (hex)> <keyblock file (binary)>

**Comment by jvillarrealn** [comment]
Yes i'm Javier.
i used the DEK you sent me and tried the loop method and my device was /dev/loop0
but when i try to mount it always tells me to specify the Filesystem type. if i specify msdos as Filesystem type it return with an invalid filesystem type.

so im back at sqquare one.
now trying to install reallymine.





On themaddoctor <notifications@github.com>, Oct 19, 2017 6:15 PM wrote:

You are Javier, correct?

Your DEK is unique to your disk. No other DEK will work.

bash sw6316-extract-DEK-from-keyblock.sh <kek file (hex)> <keyblock file (binary)>

**Comment by themaddoctor** [comment]
Can't help you without the 2MB dump

**Comment by jvillarrealn** [comment]
Here is the 2MB dump.  hope i did it right.

i'm sending a RAR file and the bin.  in case hotmail blocks bins.


thank you.


________________________________

**Comment by jvillarrealn** [comment]
seems like the file didn't attach, here is another try.
[2mfile.zip](https://github.com/themaddoctor/linux-mybook-tools/files/1402172/2mfile.zip)

**Comment by themaddoctor** [comment]
When decrypted, you have an NTFS partition starting at sector 2048. There is no other partition in the partition table. Use the instruction in the section "Mounting with a loop device."

**Comment by jvillarrealn** [comment]
i tried with the looped drive procedure:
both dd's:
sudo dd if=/dev/sda skip=2048 count=16 | file -
sudo dd if=/dev/mapper/wd skip=2048 count=16 | file -
returned data, as in your guide.
then did the losetup's and the second one returned:
/dev/loop0
so i tried to mount:
sudo mount /dev/loop0 /mnt/wd 
and returned that i must specify a Filesystem type.
then tried:
sudo mount -t msdos /dev/loop0 /mnt/wd
and returned  "wront fs type, bad option, bad superblock, or other error" etc etc...
i also tried :  sudo mount -t ntfs /dev/loop0 /mnt/wd    to the same error result, 
any other ideas please?
thank you

**Comment by themaddoctor** [comment]
The file system type is ntfs-3g
It is not msdos

**Comment by jvillarrealn** [comment]
i just did:
sudo mount -t ntfs-3g /dev/loop0 /mnt/wd
returned:
mount: unknown filesystem type

**Comment by jvillarrealn** [comment]
ok Doc,  i did an installation of the ntfs-3g support filesystem and tried again.
this time the sudo mount -t ntfs-3g /dev/loop0 /mnt/wd
returned:
_**"Failed to mount '/dev/loop0' doesn't seem to have a valid NTFS.
Mayber the wrong device is used? or the whole disk instead of a partition (e.g. /dev/sda, not /dev/sda1)? or the other way aournd?"**_
hope this opens more possibilities.

**Comment by themaddoctor** [comment]
Either you didn't set up decryption correctly, or your filesystem is corrupted.

dd if=/dev/loop0 count=16 | file -

I don't know anything useful about Windows filesystems.

**Comment by jvillarrealn** [comment]
I tried everything again and the strange thing is that the unwrap.py keeps giving the same error about "odd-length string".
Im wondering if the Raspian OS on my raspberry pi is the culprit. 
Why can't i obtain my own DEK, i also tried your bash for the symwave and gave me a bunch of errors.
I'll create a USB Linux boot and try with that.
Thanks

**Comment by themaddoctor** [comment]
I GAVE YOU YOUR DEK. WHY ARE YOU TRYING TO FIND IT AGAIN?

**Comment by jvillarrealn** [comment]
Because right now i don't know what else to try. I'd like to think that i gave you something wrong on the files and that the DEK is not right. Otherwise im screwed. What else would you try. 
I can't mount it with the loop procedure either. 
If you have any ideas i coule try, please let me know and i'll try them.
Right now im creating a dvd boot disk for linux on another machine just in case my raspberry pi is screwing me over.
Thanks doc.

**Comment by themaddoctor** [comment]
THE DEK IS CORRECT. I USED IT TO DECRYPT THE 2MB SAMPLE THAT YOU SENT.
cbc052c557ed061c5c6a15fae63311245f722271a22d0052525381b1a81606a8

**Comment by jvillarrealn** [comment]
So what is the veredict?.  Why can't mount my drive. Anything i could try?. What would you do next?
Thanx

**Comment by themaddoctor** [comment]
I WOULD DOUBLE-CHECK MY CRYPTMOUNT COMMAND, LIKE I HAVE BEEN SAYING

**Comment by themaddoctor** [comment]
Use the DEK with ReallyMine to make a decrypted copy of the disk. Connect the new disk to your Windows machine. Ask Windows what's wrong with the filesystem.

**Comment by jvillarrealn** [comment]
ok, i made some progress !!!.  i retyped the CRYPSETUP and now the sudo file -sL returns something more promisimg:
/dev/mapper/wd: sticky x86 boot sector: partition 1: ID=0x7, starthead 4, startsector 256, 536870656 sectors, extended partition table (last)\011, code offset 0x0
i did the kpartx with no error and then tried to mount, but it says:
/dev/mapper/wd already mounted or /mnt/wd busy
if its already mounted why can't i cd to it?.  i can't see this path (/mnt/wd).
i think i'm almost there, just need a little help.
some more info,  if i do:  sudo cat /proc/partitions, i see 3 new entries like this:
8         0        2930266584   sda
254     0        2930266584   dm-0
254     1        2930266584   dm-1

thanks

**Comment by jvillarrealn** [comment]
Bit more info,  i did the loop check commands and these are the results:
sudo fdisk -s /dev/sda
2930266584
sudo dd if=/dev/sdc skip=2048 count=16 | file -
/dev/stdin: data
sudo fdisk -s /dev/mapper/wd
2930266584
sudo dd if=/dev/mapper/wd skip=2048 count=16 | file -
/dev/stdin: x86 boot sector, code offset 0x52, OEM-ID "NTFS   ", bytes/sector 4096, reserved sectors 0, Media descriptor 0xf8, heads 255, hidden sectors 256, dos < 4.0, bootsector (0x80)

hope you can guide me to the light with this info.. 
thanks in advance.

**Comment by themaddoctor** [comment]
Use the loop device. Your partition table is broken. Do not use kpartx.

**Comment by themaddoctor** [comment]
INFO:fontmake.font_project:Saving OTF for NotoSans-BoldItalic
You shouldn't map the same device twice. You have to 
sudo cryptsetup remove wd
before you redo the decryption filter.

**Comment by jvillarrealn** [comment]
ok, i'm doing the looped mount and there is activity on the drive and the  sudo mount /dev/loop0 /mnt/wd hasn't finished, is this normal?.  it's been like 5 minutes.

**Comment by jvillarrealn** [comment]
ok it finished with no errors.  i guess it mounted it, but not how do i access it.
i can't cd to it.  so where is it?
thx

**Comment by jvillarrealn** [comment]
my friend sorry for all the trouble,  it mounted and now i can see my files.
i'm very happy.  i appretiate your time.

thank you so much
