### ISSUE TITLE
Trying to Follow the guide on mounting encrypted drive but need assistance

### ISSUE THREAD

**Issue by AlanJ6** [themaddoctor/linux-mybook-tools#34]
@themaddoctor sorry to bother you but i was hoping that you could assist me and dealing with my old drive. 

I am trying to follow your guide but i am pretty much stuck at the beginning. I have taken the PCB off of my disk and it is uses a JMicron JMS538S chip. This board has a USB connector from which i used to access it. But i noticed the guide states that this should be connected to a sata port. Should i buy a new PCB with a sata port that fits the drive? 

Because otherwise I have no idea on how to connect it to my Ubuntu pc so that i can start dd the information.

I hope you can help. thanks again for the guide.

**Comment by themaddoctor** [comment]
Model? Photo?

**Comment by AlanJ6** [comment]
The model of my passport is WD10JMVW-11S5XS0. My pcb model number is 2060-771801-002 REV A

**Comment by AlanJ6** [comment]
It is a 1TB WD drive

**Comment by themaddoctor** [comment]
Sorry, passports require that you bypass the JMS538S chip. My guide is for MyBooks, which have the JMS chip on a second PCB board. But it doesn't sound like you have that kind of experience to do this on your own.

There are some guides online from people who have succeeded in bypassing the chip. Google can help you find them. Then you need to find someone who can solder or remove surface-mounted components.

Sorry.

Once you have access to the encrypted contents od the drive, I can help you decrrypt.

**Comment by AlanJ6** [comment]
Ah alright. Thank you @themaddoctor. is it possible to use andlabs/reallymine to get the contents or decrypt mypassport?

**Comment by themaddoctor** [comment]
Not unless you gain access to the encrypted contents.

**Comment by AlanJ6** [comment]
Alright thank you. I found this pdf on the drive security, got HW crypto?
On the (in)security of a Self-Encrypting Drive series. I will see what i can do with this. Thanks again.

**Comment by themaddoctor** [comment]
http://blog.acelaboratory.com/pc-3000-hdd-how-to-solder-a-sata-adapter-to-the-usb-western-digital-drive.html

**Comment by themaddoctor** [comment]
find a guide like that one, but for your model
