### ISSUE TITLE
Trouble trying to decrypt Symwave SW6316

### ISSUE THREAD

**Issue by apefist** [themaddoctor/linux-mybook-tools#4]
Hello,

I tried using your tool to decrypt a WD My Book Essential, and was having some issues.  I went through the steps in the PDF around 4 times, just to be sure I didn't mistype any commands.  I have uploaded the kb0.bin as well as the first 2MB of the drive as per the README, as well as the terminal log, just in case.

Any help is greatly appreciated, thank you

[wd.zip](https://github.com/themaddoctor/linux-mybook-tools/files/1412838/wd.zip)

**Comment by themaddoctor** [comment]
You didn't finish the instructions for mounting through a loop device.
