### ISSUE TITLE
[Solved] Recovering Files from WD My Book Elite NTFS partition with mistaken quick format

### ISSUE THREAD

**Issue by ognjenvukovic** [themaddoctor/linux-mybook-tools#41]
Hi,

Let me first thank you, greatly, for this repository and for your help! You brought me hope that I can recover my family photo collection after 5 years of not knowing what to do.

5 years ago, I accidentally broke the USB connector in my WD My Book Elite, and not knowing about the encryption, I attached the drive to my Windows 7, and because Win did not recognize the drive, I performed a **quick format**, probably to FAT 32 or maybe NTFS, I am not sure :-(. Yes, I was young and stupid. This quick format is probably now causing some interesting problems.

The device is WD My Book Elite WDBAAH0010HCH, it comes **formatted NTFS**.

I have been following your instructions for **Initio INIC-1607E chip**:
- :ok: the drive is attached as /dev/sdb (I am sure), and `sudo file -sL /dev/sdb` gives:
    >/dev/sdb: DOS/MBR boot sector MS-MBR Windows 7 english at offset 0x163 "Invalid partition table" at offset 0x17b "Error loading operating system" at offset 0x19a "Missing operating system", disk signature 0xe861fbef
- :ok: managed to successfully read the keyblock from the end of the disk, i.e., the output of `hexdump -C kb.bin` starts with "WD" 
- :ok: performed the remaining commands to create dek.hex
- :ok: built and loaded the kernel module
- :question: set up the encryption filter. First and third command start with echoing nothing `echo | sudo cryptsetup ...`, **is that correct**?
- :warning: `sudo file -sL /dev/mapper/wd` gives:
    > /dev/mapper/wd: data

**Trying Mounting**
- :question: `$ sudo kpartx -a /dev/mapper/wd` returns nothing.
- :sos: `$ sudo mount /dev/mapper/wd /mnt/wd` returns:
    > **mount: /mnt/wd: wrong fs type, bad option, bad superblock on /dev/mapper/wd, missing codepage or helper program, or other error.**
- btw. there is a **typo** in the guide, the guide targets `/dev/mapper/wd1` instead of `/dev/mapper/wd`

**Trying Mounting with a loop device**
- :warning: sudo file -s /dev/sdb
    >/dev/sdb: DOS/MBR boot sector MS-MBR Windows 7 english at offset 0x163 "Invalid partition table" at offset 0x17b "Error loading operating system" at offset 0x19a "Missing operating system", disk signature 0xe861fbef
- :warning: sudo dd if=/dev/sdb skip=2048 count=16 | file -
    > 16+0 records in
16+0 records out
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.000355676 s, 23.0 MB/s
/dev/stdin: DOS/MBR boot sector, code offset 0x52+2, OEM-ID "NTFS    ", sectors/cluster 8, Media descriptor 0xf8, sectors/track 32, heads 64, hidden sectors 2048, dos < 4.0 BootSector (0x80), FAT (1Y bit by descriptor); NTFS, sectors/track 32, sectors 1953519615, $MFT start cluster 786432, $MFTMirror start cluster 2, bytes/RecordSegment 2^(-1*246), clusters/index block 1, serial number 0f442ed7842ed404a; containsMicrosoft Windows XP/VISTA bootloader BOOTMGR
- sudo file -s /dev/mapper/wd
    >/dev/mapper/wd: symbolic link to ../dm-2
- :warning: sudo file -s /dev/dm-2
    >/dev/dm-2: data
- :warning: sudo dd if=/dev/mapper/wd skip=2048 count=16 | file -
    >16+0 records in
16+0 records out
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.000610648 s, 13.4 MB/s
/dev/stdin: data
- :ok: sudo losetup -o 1048576 -f /dev/mapper/wd
- :ok: sudo losetup -j /dev/mapper/wd
    > /dev/loop18: [0006]:614 (/dev/dm-2), offset 1048576
- :ok: sudo mkdir -p /mnt/wd
- :sos: sudo mount /dev/loop18 /mnt/wd
    > mount: /mnt/wd: wrong fs type, bad option, bad superblock on /dev/loop18, missing codepage or helper program, or other error.

**Any ideas how to proceed?**

I cannot express my gratitude to any help that would help me recover old family photos...

**==== Update ====**:

Because I have formatted the drive, that made the recovery more difficult. What worked for me:
1. Run: ddrescue /dev/mapper/wd /path/to/new/disk/or/dumpfile
2. Run a file recovery software (e.g., EaseUS), which managed to recover most file names and folders as it was NTFS.

**Comment by themaddoctor** [comment]
Your problem is that you formatted the drive. That overwrote the filesytem that was originally there.
If you copy the disk through the decryption filter with a command like "ddrescue /dev/mapper/wd /path/to/new/disk/or/dumpfile", then you can do data recovery on the copy. There are programs like photorec that you can try for recovering files from a disk image.

The only thing I can do for you at this point is try to verify that the decryption is working by looking at chunk of data from the middle of the disk. And I can only do that if you have not written anything
else onto the disk since the time that you formatted it.

**Comment by themaddoctor** [comment]
Just so it's clear: You will not be able to mount the disk and copy your files, because your filesystem was destroyed. Photos will have to be carved out of the disk image.

**Comment by ognjenvukovic** [comment]
Thank you @themaddoctor, that worked and helped me!

Since my partition was NTFS, I have managed to recover quite some file names and folder structure. In particular, I used EaseUS.

**Comment by themaddoctor** [comment]
Good news. Thanks for letting me know.
