### ISSUE TITLE
When MBR is corrupt on MAC disks/Timemachine

### ISSUE THREAD

**Issue by barnabe** [themaddoctor/linux-mybook-tools#48]
Hello and thank you for this great tool box!
I am trying to recover a disk that once was a Mac timemachine using ubuntu. The decryption part works fine but my MBR is corrupt it seems and I cannot mount the disk. 

In your pdf you write that "For Mac drives, probing the GPT partition table starting in sector 1 may help you to find the location of your data partition." Can you be a bit more specific please? i tried "sudo losetup -o 1048576 -f /dev/mapper/wd" (why 1048576? is it because is it the product of 2048 and 512?) but no luck. 

If you have any idea of where i should look for the data section of the disk that would be most helpful. 

Thanks!

**Comment by themaddoctor** [comment]
See if you have a GPT partition table in sector 1. Sector 1 starts at byte 512.

**Comment by themaddoctor** [comment]
The command that you said you tried is for NTFS Windows disks.

**Comment by barnabe** [comment]
> The command that you said you tried is for NTFS Windows disks.

Yes you documentation says so. I just had to try something

**Comment by barnabe** [comment]
> See if you have a GPT partition table in sector 1. Sector 1 starts at byte 512.

thanks
