### ISSUE TITLE
PLX OXUF943SE keyblock 

### ISSUE THREAD

**Issue by JosephPua** [themaddoctor/linux-mybook-tools#56]
Hi, I've recently come across this tool and tried to follow the instructions. However, I got stuck at trying to obtain the keyblock (as shown in the screenshot. I have a 2TB My Book with PLX OXUF943SE - the device is assigned sde.
![Screenshot from 2020-09-06 22-37-21](https://user-images.githubusercontent.com/29562659/92329523-82e69200-f09a-11ea-93d4-03cf94433bd9.png)

Would be really grateful if anyone could help me with this issue, Thanks! Do let me know if there's any other info I could provide that would help.

**Comment by themaddoctor** [comment]
That error indicates that /dev/sde does not contain enough blocks to skip that far. Maybe you are mistaken about which drive is the WD drive, or you didn't take it out of the enclosure and use a generic enclosure, or we are wrong about the keyblock location. Try doing lsblk to see what drives you have and their sizes.

**Comment by JosephPua** [comment]
Here's a screenshot with lsblk. Some more details on my setup: sda is my internal drive, sdd is my bootable ubuntu drive.

Not sure why I have 3 partitions, but this drive was previously formatted in HFS+. I've tried the keyblock locations for the other chipsets as well, all the others returned something along the lines of 00000000000 (I assume because nothing was located there - I can take a screenshot if needed).

![Screenshot from 2020-09-07 08-40-57](https://user-images.githubusercontent.com/29562659/92338972-4cceff80-f0e6-11ea-84e0-b1f358d03426.png)

**Comment by themaddoctor** [comment]
It might not be encrypted. Have you tried opening it with a Mac?

**Comment by JosephPua** [comment]
Under OSX:
1. With Generic Enclosure: Disk is not readable
2. With the original enclosure's chipset with PLX OXUF943SE: Drive mounts, but is extremely slow in accessing data - I'm unable to retrieve my data (this led me to believe the controller has problems and how I ended up searching for the program you made)

**Comment by JosephPua** [comment]
Given the details above, I can't access my files with a generic enclosure or with the original enclosure. This hard drive still has some data (which I can see but cant extract with the original enclosure in OSX), so I was wondering if there's anything else that we can try.

Is there a possibility that the keyblock location could be somewhere else? As I noted from the pdf that the keyblock location for this combination of drive size and chip was uncertain.

**Comment by themaddoctor** [comment]
If you can see the data in OSX (i.e. see the filenames) but not copy the files, then try using sudo in the Terminal App. The sudo
command works the same on OSX as in linux.

With the PLX chip, people have had almost no luck finding the key elsewhere. You could try dumping the service-area modules with HDDSuperTool (google knows where to find it). Or it could be stored in a memory chip on one of the boards. I'm sorry there isn't an easy answer.

**Comment by JosephPua** [comment]
Thanks for advice, I'll see if HDDSuperTool can help with dumping the modules.
