### ISSUE TITLE
WD 2TB split in two almost equal sizes instead of just one

### ISSUE THREAD

**Issue by CSilva4** [themaddoctor/linux-mybook-tools#57]
Hello Thomas,

Thank you very much for your hard work, support and giving people like myself the hope that not everything is lost.

I have a 2TB WD Book that stopped turning on a few weeks back, long story short, after I found out that this drive is encrypted by default, I ended up discovering your tool, so I proceeded trying to recover my life that is on the disk (wedding, honey moon photos, college works, etc), the chip is a JMS538S.

Following your pdf Tutorial, the /proc/partitions output is the following (the WD Disk is the one pointed in red):
![image](https://user-images.githubusercontent.com/71497995/93593139-09587900-f9a3-11ea-8687-19e70925e3e5.png)

I was worried since in your pdf says it should be a single sdb, but in my case is two, sdb and sdb1, however, i continued the tutorial with sdb1 since it was the one who said /dev/sdb1: data

I had no password in the disk, so used the standard KEK, however, I was only able to find the keyblock using your search program, otherwise I couldn't get it.
![image](https://user-images.githubusercontent.com/71497995/93593768-335e6b00-f9a4-11ea-97fd-a072845402c8.png)
Everything look normal so I continue, the kb3.bin result is as follow:
![image](https://user-images.githubusercontent.com/71497995/93593970-889a7c80-f9a4-11ea-940f-54537c32a765.png)
Still feels like everything is going to plan, reversed to get the correct DEK and continued.

I also been able to compile the rev16 as per your tutorial with success I think, and all 3 commands are successful, but when I check for success in mounting the drive it just show as data again... (the 3 commands show as it already exists because I just repeated the process to show you the commands I used)
![image](https://user-images.githubusercontent.com/71497995/93594706-dfed1c80-f9a5-11ea-8ff5-7f362968a745.png)

So this led me to the "mounting with a loop device" part, the outputs are as follow, but I'm not sure if this is done on the /dev/sdb or /dev/sdb1 or whatever since all show different results (in this case the output is for sdb1):
![image](https://user-images.githubusercontent.com/71497995/93595511-69e9b500-f9a7-11ea-8584-601417e52a46.png)

My suspicions are that this issue is due to the fact that the drive appears as sdb and sdb1 instead of a full sdb and I need somehow solve that first, but that is completely out on my knowledge. I also put the result files attached so you can have a closer look at them.
[wd.zip](https://github.com/themaddoctor/linux-mybook-tools/files/5245387/wd.zip)

If you need any other input from me in order to help pinpoint where the issue is, I will be at your services.

Thank you once again for your availability.

**Comment by themaddoctor** [comment]
The fact that sdb1 appears, and has a size that nearly fills sdb, indicates that the disk was repartitioned after you removed it
from the WD enclosure. The reason the keyblock was not where you expected is that sdb1 starts 1MB into the disk. Using
the loopback method also cannot work, because you are now trying to find a partition that is 2MB into the disk, rather than
only 1MB.

We can check whether the drive is truly encrypted and whether it was repartitioned or reformatted by looking at some sectors.
Please do a hexdump of sectors 0, 2048, and 2049 of sdb (not sdb1):
sudo dd if=/dev/sdb count=1 skip=0 status=none | hexdump -C
sudo dd if=/dev/sdb count=2 skip=2048 status=none | hexdump -C

**Comment by themaddoctor** [comment]
p.s. What is the manufacture date written on your disk's label?

**Comment by themaddoctor** [comment]
You "initialized" the disk in Windows after you took it out of the WD enclosure, CONTRARY TO MY ADVICE in the guide. As a
result, you have a new MBR with a new partition table, and the first sector of your data partiion has been overwritten with zeroes.

I have a possible fix, but it is not guaranteed. I have a copy of sector 2048 from another disk. Sector 2049 from that disk
matches sector 2049 from your disk (after decryption), so it might be that sector 2048 of that disk matches your old
sector 2048 before it was corrupted.

Here is a hexdump of the replacement sector 2048:
eb52904e5446532020202000020800000000000000f800003f00ff0000080000
0000000080008000ff7fdfe80000000000000c00000000000200000000000000
f6000000010000009f754318b34318f26afcca63fa33c08ed0bc007cfb68c007
1f1e686600cb88160e0066813e03004e5446537515b441bbaa55cd13720c81fb
55aa7506f7c101007503e9dd001e83ec18681a00b4488a160e008bf4161fcd13
9f83c4189e581f72e13b060b0075dba30f00c12e0f00041e5a33dbb900202bc8
66ff06110003160f008ec2ff061600e84b002bc877efb800bbcd1a6623c0752d
6681fb54435041752481f90201721e166807bb1668700e166809006653665366
5516161668b80166610e07cd1a33c0bf2810b9d80ffcf3aae95f01909066601e
0666a111006603061c001e66680000000066500653680100681000b4428a160e
00161f8bf4cd1366595b5a665966591f0f82160066ff06110003160f008ec2ff
0e160075bc071f6661c3a0f801e80900a0fb01e80300f4ebfdb4018bf0ac3c00
7409b40ebb0700cd10ebf2c30d0a41206469736b2072656164206572726f7220
6f63637572726564000d0a424f4f544d4752206973206d697373696e67000d0a
424f4f544d475220697320636f6d70726573736564000d0a5072657373204374
726c2b416c742b44656c20746f20726573746172740d0a008ca9bed6000055aa

1. Start over by rebooting your linux machine.
2. Set up the decryption layers on sdb (not sdb1).
3. Paste the hexdump above into a file; call it new2048.hex
    Only include the lines of hex. The file new2048.hex should be 1040 bytes long.
4. Insert the new sector 2048. Do not make any mistakes. Here is the command:
xxd -p -r new2048.hex | dd of=/dev/mapper/wd seek=2048 conv=notrunc
5. Wait 10 seconds to see if linux recognizes the partition automatically. If not, use the loopback method.

Hope that works. Let me know what happens.

**Comment by CSilva4** [comment]
Ok, so, before I do anything stupid, I rebooted the machine, initialized the decryption engine as you see in the image below and checked for the position of the disk, which is now a sdc and sdc1 (might be because I disconnected it before turning the pc on again)
![image](https://user-images.githubusercontent.com/71497995/93616222-fa35f300-f9c3-11ea-9165-e85c0713d6ff.png)

I have created the Hex file with what you told to copy into it
![image](https://user-images.githubusercontent.com/71497995/93617273-4897c180-f9c5-11ea-99fc-09670020d0f5.png)

It gave a warning about having already a dos signature, I'm just checking with you if this is normal before doing your command
![image](https://user-images.githubusercontent.com/71497995/93616651-87794780-f9c4-11ea-98f6-4699c2e4a993.png)

The instruction is already written, just waiting for your confirmation about this dos thing before pressing enter
![image](https://user-images.githubusercontent.com/71497995/93617789-f2774e00-f9c5-11ea-9189-475d6b41388c.png)

**Comment by CSilva4** [comment]
Well, gained the courage and hit enter,
Permission Denied. Added sudo in the beginning, Permission Denied as well...

![image](https://user-images.githubusercontent.com/71497995/93623703-a67cd700-f9ce-11ea-90df-d1f44b406d7e.png)

What should I do now? Does this have to do with the dos thing?

**Comment by themaddoctor** [comment]
My mistake. Put sudo with dd:
 xxd -p -r new2048.hex | sudo dd of=/dev/mapper/wd seek=2048 conv=notrunc

**Comment by themaddoctor** [comment]
p.s. Don't wait for the system to autodetect. Use the loopback method.

**Comment by CSilva4** [comment]
Thank you, Thank you, Thank you!

I cannot thank you enough! after putting your instruction with sudo, it went through, after that, it was still showing the sdc and sdc1 on the /proc/partitions, I ignored that since you told me to stick with sdc only.

So I did the loopback process on sdc, and as soon I mounted the loop1 (my case)
![image](https://user-images.githubusercontent.com/71497995/93644348-5400e200-f9f1-11ea-89cc-517d293878af.png)

Bang! a warning about fixing because of an unclean file system.

When it ended, I went strait to /mnt/wd and here it is! All the folders, files, photos, all there, and I even thought the partition tree was damaged, turns out it was solely the decryption. It is safe to say that you saved my marriage Thomas! hehe :)

I will now, before turning the PC off, backup the entire disk to another one, and only after I will turn this off and reformat this to remove the decryption.

Thank you once again, and if you need some data or info from my disk for your database, please let me know, I will gladly give it to you before formatting it.

**Comment by themaddoctor** [comment]
That's good news. Make two copies of all your data, just to be sure. And always back up your stuff.

**Comment by CSilva4** [comment]
I will start to do that for sure, this is a lesson learned for me.

Thank you once again, you are awesome!
