### ISSUE TITLE
Mybook Studio 3TB

### ISSUE THREAD

**Issue by mcbrab** [themaddoctor/linux-mybook-tools#6]
Hi, I'm trying to find the keyblock from my 3TB harddrive, but I get invalid argument when trying the skip-values specified in your pdf.

I've done a dump of the last sectors that i'm able to read and they contain readable strings (seen using hexdump -C ) like WD Unlocker and OSTA UDF Compliant.

I do have a dump of the first partition of the drive made by ddrescue before i removed the usb-interface and a partial dump of the second partition (unencrypted).

I never set a password, can I somehow, without reattaching the USB-SATA interface find the needed encryption key?

**Comment by themaddoctor** [comment]
Maybe. What chip is on the USB-SATA card?

**Comment by mcbrab** [comment]
The enclosure is a My Book Studio with usb-2 and FW800. 
The disk is WD30EZRX-00DC0B0
The chip is a PLX OXUF943SE

I've reattached the my book usb-sata-bridge, but i still get invalid argument with your suggested sector

sudo dd if=/dev/sdd of=test.bin bs=512 skip=5860533120 count=1
dd: /dev/sdd: cannot skip: Invalid argument
0+0 records in
0+0 records out
0 bytes copied, 8.314e-05 s, 0.0 kB/s

Dumping the same sector with hddsupertool gives me something, but it looks like data so I don't know if it wraps?

`
00000000  00 70 00 6c 00 65 00 2e  00 73 00 79 00 73 00 74  |.p.l.e...s.y.s.t|

00000010  00 65 00 6d 00 2e 00 53  00 65 00 63 00 75 00 72  |.e.m...S.e.c.u.r|

00000020  00 69 00 74 00 79 00 00  00 10 00 00 00 00 00 00  |.i.t.y..........|

00000030  00 00 00 00 00 44 01 2c  c1 6d 00 00 00 00 00 00  |.....D.,.m......|

00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 01 00 00  |................|

00000060  00 00 ab cd ef ab cd ef  ab cd ef ab cd ef 00 00  |................|

00000070  00 0c 00 00 00 02 00 00  25 34 00 5a 00 00 03 3f  |........%4.Z...?|

00000080  b8 35 00 00 00 00 00 27  00 63 00 6f 00 6d 00 2e  |.5.....'.c.o.m..|

00000090  00 61 00 70 00 70 00 6c  00 65 00 2e 00 66 00 69  |.a.p.p.l.e...f.i|

000000a0  00 6e 00 64 00 65 00 72  00 2e 00 63 00 6f 00 70  |.n.d.e.r...c.o.p|

000000b0  00 79 00 2e 00 73 00 6f  00 75 00 72 00 63 00 65  |.y...s.o.u.r.c.e|

000000c0  00 2e 00 63 00 68 00 65  00 63 00 6b 00 73 00 75  |...c.h.e.c.k.s.u|

000000d0  00 6d 00 23 00 4e 00 00  00 10 00 00 00 00 00 00  |.m.#.N..........|

000000e0  00 00 00 00 00 04 74 90  a2 fd 00 00 00 00 00 00  |......t.........|

000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

`

I also did a dump of a bunch of modules using hddsupertool and tried to grep for SiNE but to no avail. However, maybe thats the wrong string to grep for when the drive is used via the interface that makes it look unencrypted...

Any ideas?

**Comment by themaddoctor** [comment]
First of all, sectors at the end of the disk are hidden by the SATA bridge. You can only access them after the bridge card is removed.

Please attach the bare drive to your linux computer and dump the first 2MB so we can see if it really is encrypted.

sudo dd if=/dev/sdX count=4096 | hexdump -C
(replace sdX with the right thing)

**Comment by mcbrab** [comment]
Here are sectors 0-50 both encrypted and not. 

If thats not enough I'll provide more during the weekend.  I've got comparatively good speed now (5MB/s) on my ddrescue session...

[0-50.txt](https://github.com/themaddoctor/linux-mybook-tools/files/1519041/0-50.txt)
[0-50-dec.txt](https://github.com/themaddoctor/linux-mybook-tools/files/1519042/0-50-dec.txt)

**Comment by themaddoctor** [comment]
Now let's see what's at the end of the disk:
sudo dd if=/dev/sdX skip=5860533000 | hexdump -C

**Comment by mcbrab** [comment]
I found the keysector, it was where you've said it should be. When I connected the drive through an ordinary sata-usb interface I was able to follow the instructions per the pdf.

Closing the issue.

**Comment by themaddoctor** [comment]
Would you bee so kind as to donate a copy of sectors 5860533120 through 5860533128 for testing purposes? TY

**Comment by mcbrab** [comment]
Hi, I can only donate the key sector at the moment. Will try and get you more.

[5860533120.zip](https://github.com/themaddoctor/linux-mybook-tools/files/1524055/5860533120.zip)

**Comment by mcbrab** [comment]
Hi, there was nothing more between 120 and 128, but here is a dump from 120 to the end of the disc. The encryption key was duplicated.


[5860533120_end.zip](https://github.com/themaddoctor/linux-mybook-tools/files/1525065/5860533120_end.zip)

**Comment by themaddoctor** [comment]
Thank you!
