### ISSUE TITLE
WD MyBook 12TB drive cannot be recognized

### ISSUE THREAD

**Issue by nenchi** [themaddoctor/linux-mybook-tools#71]
Hello, I  would like to ask if there is possibility to fix my drive. I bought WD MyBook for Synology, when drive came, I put it out and connect it directly via SATA to Synology. Then I tried to format it and then my problems begin, because drive couldn't be formatted. I try it later connecting via original USB-adapter and drive was recognized like 0TB and I couldn't format it in Windows, neither Linux or MacOS. I tried connecting directly to PC over SATA, but drive can't be detected. Drive powers up, you hears that works, but there is no possibility to be found or be formatted. I tried with some used USB board from MyBook and drive could be detected, but cannot be formatted. So know my question is, can be something done or should I forget about drive? It would be nice if could someone with more experiences can give me some advice if there is any.

Hard Drive model:
Western Digital WD120EDAZ

MDL: WD120EDAZ-11F3RA0 

Manufactured: 05 DEC 2020

**Comment by themaddoctor** [comment]
Sorry, but I don't know anything about that model.
If you can put it back together, maybe WD will still honor its warranty.

**Comment by nenchi** [comment]
> Sorry, but I don't know anything about that model.
> If you can put it back together, maybe WD will still honor its warranty.

Thank you for your fast reply. I think I will wait a little and maybe try to do that.
