### ISSUE TITLE
(Symwave SW6316 chip)     TypeError: Odd-length string

### ISSUE THREAD

**Issue by Matrix-Coder1** [themaddoctor/linux-mybook-tools#73]
First of all, thanks for all your hard work with this project!

I have a 3TB that began to disappear on Windows. I plug it in and a drive letter shows, but cannot open it. I believe the problem is with the USB-SATA card. I have the SW6316. I do not believe I had password protected the drive. I believe there are a few programs on there I wrote in high school in the 1990s and would just like to see if they were on there.

 I cannot get past the unwrapping the DEK. 

The error is a Python Traceback:
File "./unwrap.py", line 31, in <module>
CIPHER = binascii.unhexlify(sys.argv[1])
TypeError: Odd-length string

With my limited programming knowledge I believe this to be an issue with what's passed to argv[1]. I've added a space after the first filename in the calling command like:
./unwrap.py 'xxd -p -c 40 edek.bin ' 'cat kek.hex' > dek0.hex

But then I get a different Python Traceback:
File "./unwrap.py", line 31, in <module>
CIPHER = binascii.unhexlify(sys.argv[1])
TypeError: Non-hexadecimal digit found

I was hoping you could point me in the right direction with minimal time out of your day - I've spent 3 whole days on this now.

I've even purchased another drive hoping to get a donor USB-SATA card, but it came with the USB socket removed and it was also the wrong chipped card.

-James

**Comment by themaddoctor** [comment]
You need to use the left-single-quote key, not the apostrophe. The left single quote is on the same key as tilde (~) on an American keyboard. I can't type it here, because it also is a special character in markdown.

**Comment by Matrix-Coder1** [comment]
Wow. Thx! I'll give that a try.

**Comment by Matrix-Coder1** [comment]
Yes. That was it. Now I just need to figure out the best practical way to copy from my virtual machine. Thank you very much!
