### ISSUE TITLE
How to know if my WD is really encrypted

### ISSUE THREAD

**Issue by madgarlic** [themaddoctor/linux-mybook-tools#78]
Hello, 

my 3TB WD MyBook stopped turning on, so I removed the HDD from the original case and put it in another non-WD one just to discover that it cannot be accessed like before. 
Plugging the disk into my Mac, it popped up the "The disk you attached was not readable by this computer" message, to which I always replied "Ignore".
Tried one time to use it in Windows 10 on VMWare without success but I understand that it might have messed somehow with MBR even if didn't reformat the drive.
Then I installed ubuntu and tried reallymine: "getkek" doesn't seem to do give a result.

So now I am trying with "the pdf" but I can't get past the keybloc part. Unfortunately, I already threw away the original WD enclosure and its board, so I don't know the model and I don't know the chip.

Here is some output:

```
cat /proc/partitions 

major minor  #blocks  name

   7        0          4 loop0
   7        1      63380 loop1
   7        2      44676 loop2
   7        3      63380 loop3
   7        4      55540 loop4
   7        5      45708 loop5
   7        6      66776 loop6
   7        7     254728 loop7
  11        0    1048575 sr0
   8        0   20971520 sda
   8        1     524288 sda1
   8        2   20445184 sda2
   8       16 2930233816 sdb
```
```
sudo file -s /dev/sdb

[sudo] password for mario: 
Sorry, try again.
[sudo] password for mario: 
/dev/sdb: DOS/MBR boot sector; partition 1 : ID=0xee, start-CHS (0x3ff,254,63), end-CHS (0x3ff,254,63), startsector 1, 732558335 sectors, extended partition table (last)
```
```
sudo fdisk -l /dev/sdb

GPT PMBR size mismatch (732558335 != 5860467632) will be corrected by write.
Disk /dev/sdb: 2,75 TiB, 3000559428096 bytes, 5860467633 sectors
Disk model:                 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x5467052d

Device     Boot Start        End    Sectors Size Id Type
/dev/sdb1           1 4294967295 4294967295   2T ee GPT

Partition 1 does not start on physical sector boundary.
```

Then I tried to determine the keybloc with every 3Tb value in the pdf with the command below, always getting "cannot skip: invalid argument" 
```
sudo dd if=/dev/sdb bs=512 skip=XXXXXXX count=1 of=kb.bin
```

Then I tried the sh script in appendix E
```
sudo ./findkeyblock.sh /dev/sdb

keyblock not found
```

Now I am not sure how to proceed, and not even sure that the disk is encrypted.

**Comment by madgarlic** [comment]
Yes, I've put the disk in a generic enclosure that is not from WD (the label says "SABRENT")

**Comment by themaddoctor** [comment]
Then it appears that either the disk is not encrypted, or Windows reformatted it.

**Comment by u2n** [comment]
(@madgarlic) Just a friendly tip; in case the drive is not encrypted or reformatted, connecting it directly via SATA cable and [issuing a couple of commands](https://github.com/themaddoctor/linux-mybook-tools/issues/70) should quickly reveal if the data is recoverable. Best of luck 2u!

**Comment by madgarlic** [comment]
@u2n you give me hope again! I will give it a try for sure!
