### ISSUE TITLE
Worked perfectly for 1.5TB drive with JMS538S

### ISSUE THREAD

**Issue by simpleperson123** [themaddoctor/linux-mybook-tools#99]
Thank you so much for this project, I was doing a data recovery for my relative who had invaluable data on his drive. I only had to include the header as mentioned in another issue here (running kernel 6.6), otherwise everything worked fine for me.

**Comment by themaddoctor** [comment]
Good to hear!

Looks like I will have to add that header to the instructions. Thanks.

**Comment by themaddoctor** [comment]
Would you please do me a favor? Can you check that the module rev16 compiles after you add algapi.h but also REMOVE
#include <linux/crypto.h>
?
Thanks

**Comment by simpleperson123** [comment]
I don't have my laptop with me right now, but I will try it and answer back.

**Comment by themaddoctor** [comment]
OK, thanks.

**Comment by simpleperson123** [comment]
I can confirm that rev16 compiles even without "#include <linux/crypto.h>"

**Comment by themaddoctor** [comment]
Beautiful. Thank you.
